mst_planner:
  ros__parameters:
    dt: 0.1
    v_max:
      x: 1.0
      y: 1.0
      z: 1.0
      yaw: 0.5
    v_min:
      x: -1.0
      y: -1.0
      z: -1.0
      yaw: -0.5
    a_max:
      x: 0.5
      y: 0.5
      z: 0.2
      yaw: 0.1
    a_min:
      x: -0.5
      y: -0.5
      z: -0.2
      yaw: -0.1